Repository Kernel360/hackathon2-post-season, pull requests merged in 2024-07, with the labels that each got.

#9 feat: f&b json 파일 생성
  src/utils/constants/f&b.json
Labels: feat

#8 feat: 날씨 api 적용 및 온도 표시
  package-lock.json
  package.json
  src/assets/svg/cloud-rain-wind.svg
  src/assets/svg/cloud-sun.svg
  src/assets/svg/cloudy.svg
  src/assets/svg/sun.svg
  src/hooks/utils/useWeather.js
  src/pages/MainPage/components/ClubSection/ClubSection.jsx
  src/pages/MainPage/components/ClubSection/ClubSection.styled.js
  src/pages/MainPage/components/ClubSection/ClubWeather.jsx
  src/pages/StadiumPage/StadiumPage.styled.js
  src/utils/date/getCurrentDate.js
  src/utils/date/getCurrentSharpTime.js
Labels: feat

#12 refactor: 위도/경도 롤백 완료
  src/pages/MainPage/components/ClubSection/ClubSection.jsx
Labels: refactor

#18 feat: 날씨 data redux state 에 적용
  src/hooks/utils/useWeather.js
  src/pages/MainPage/components/ClubSection/ClubWeather.jsx
  src/redux/actions/counterAction.js
  src/redux/actions/weatherAction.js
  src/redux/reducers/index.js
  src/redux/reducers/weatherReducer.js
Labels: feat

#21 design: Mainpage 디자인 수정
  src/assets/jpg/jamsilst.jpg
  src/assets/jpg/lionspark.jpeg
  src/assets/jpg/sajik.jpg
  src/pages/MainPage/components/ClubSection/ClubSection.jsx
  src/pages/MainPage/components/ClubSection/ClubSection.styled.js
  src/pages/MainPage/components/ClubSection/ClubWeather.jsx
Labels: design

#23 [feat] f&b 섹션 구현
  src/pages/MainPage/components/RestaurantSection/RestaurantCard/RestaurantCard.jsx
  src/pages/MainPage/components/RestaurantSection/RestaurantCard/RestaurantCard.styled.js
  src/pages/MainPage/components/RestaurantSection/RestaurantSection.jsx
  src/pages/MainPage/components/RestaurantSection/RestaurantSection.styled.js
  src/pages/StadiumPage/StadiumPage.jsx
  src/utils/constants/f&b.json
Labels: feat
